server {
    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;

    server_name gestion.lyceepagnidibsom.com;

    root /var/www/lycee-pagnidibsom-logiciel/app-source/public;
    index index.php index.html;

    charset utf-8;
    client_max_body_size 50M;

    include /etc/nginx/snippets/lpp-security-headers.conf;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.5-fpm.sock;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    ssl_certificate /etc/letsencrypt/live/gestion.lyceepagnidibsom.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gestion.lyceepagnidibsom.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;

    server_name gestion.lyceepagnidibsom.com;

    if ($host = gestion.lyceepagnidibsom.com) {
        return 301 https://$host$request_uri;
    }

    return 404;
}
