<?php

return [
    'categories' => [
        'getting-started' => [
            'title' => 'Démarrage',
            'description' => 'Prendre en main son compte et préparer l’établissement.',
        ],
        'students' => [
            'title' => 'Élèves et inscriptions',
            'description' => 'Créer les dossiers, rattacher les parents et organiser les classes.',
        ],
        'finance' => [
            'title' => 'Finances',
            'description' => 'Configurer les tarifs, encaisser et produire les états financiers.',
        ],
        'school-life' => [
            'title' => 'Vie scolaire',
            'description' => 'Suivre les présences, les sorties et les emplois du temps.',
        ],
        'pedagogy' => [
            'title' => 'Notes et examens',
            'description' => 'Évaluations, bulletins, conseils de classe et examens blancs.',
        ],
        'documents' => [
            'title' => 'Communication et documents',
            'description' => 'Informer les familles et produire les documents officiels.',
        ],
        'administration' => [
            'title' => 'Administration',
            'description' => 'Personnel, permissions, sécurité, journal et sauvegardes.',
        ],
    ],

    'topics' => [
        'dashboard' => [
            'category' => 'getting-started',
            'title' => 'Lire le tableau de bord',
            'summary' => 'Comprendre les indicateurs, alertes et raccourcis adaptés à votre rôle.',
            'route' => 'dashboard',
            'permissions' => [],
            'roles' => ['Tous les utilisateurs'],
            'keywords' => ['accueil', 'indicateurs', 'alertes', 'raccourcis'],
            'steps' => [
                'Ouvrez Tableau de bord depuis le menu Accueil.',
                'Consultez les alertes importantes avant de commencer les opérations de la journée.',
                'Utilisez les actions rapides pour ouvrir directement une création d’élève, un paiement, un pointage ou un bulletin.',
                'Les chiffres affichés dépendent de vos permissions : l’absence d’un bloc financier est normale pour un rôle non comptable.',
            ],
            'tips' => [
                'Actualisez la page après une opération importante pour voir les indicateurs mis à jour.',
            ],
        ],
        'profile' => [
            'category' => 'getting-started',
            'title' => 'Gérer son profil et son mot de passe',
            'summary' => 'Mettre à jour ses informations personnelles et choisir un mot de passe sûr.',
            'route' => 'profile.show',
            'permissions' => [],
            'roles' => ['Tous les utilisateurs'],
            'keywords' => ['compte', 'mot de passe', 'sécurité', 'profil'],
            'steps' => [
                'Cliquez sur votre nom en haut de la page.',
                'Corrigez votre nom, votre adresse e-mail ou votre téléphone, puis enregistrez.',
                'Dans la section Mot de passe, saisissez le mot de passe actuel puis le nouveau deux fois.',
                'Déconnectez-vous lorsque vous utilisez un ordinateur partagé.',
            ],
            'tips' => [
                'Ne partagez jamais votre mot de passe, même avec un autre membre du personnel.',
            ],
        ],
        'academic-years' => [
            'category' => 'getting-started',
            'title' => 'Configurer l’année scolaire et les périodes',
            'summary' => 'Créer l’année, les trimestres et les périodes de saisie des notes.',
            'route' => 'academic-years.index',
            'permissions' => ['academic_years.manage'],
            'roles' => ['Administrateur'],
            'keywords' => ['année', 'trimestre', 'période', 'activation'],
            'steps' => [
                'Créez l’année scolaire avec ses dates de début et de fin.',
                'Ajoutez les trimestres dans l’ordre officiel et vérifiez leurs dates.',
                'Activez une seule année : les classes, tarifs, inscriptions et rapports utiliseront cette année.',
                'Ne changez pas d’année active pendant une saisie de paiements ou de notes.',
            ],
            'tips' => [
                'Créez la nouvelle année avant les réinscriptions, sans supprimer l’ancienne.',
            ],
        ],
        'school-settings' => [
            'category' => 'getting-started',
            'title' => 'Paramétrer l’établissement',
            'summary' => 'Configurer l’identité, les signatures, les numéros et les pièces obligatoires.',
            'route' => 'settings.edit',
            'permissions' => ['settings.manage'],
            'roles' => ['Administrateur'],
            'keywords' => ['logo', 'adresse', 'signature', 'numérotation', 'documents requis'],
            'steps' => [
                'Renseignez le nom officiel, le sigle, les contacts et l’adresse du lycée.',
                'Ajoutez le logo et les noms des responsables qui apparaissent sur les documents.',
                'Ouvrez Numérotation pour définir les préfixes des matricules, reçus et certificats.',
                'Ouvrez Pièces obligatoires pour choisir les documents attendus dans chaque dossier élève.',
            ],
            'tips' => [
                'Vérifiez un PDF après toute modification de logo ou de signature.',
            ],
        ],
        'students' => [
            'category' => 'students',
            'title' => 'Créer et mettre à jour un dossier élève',
            'summary' => 'Enregistrer l’identité, les contacts, les parents et les informations scolaires.',
            'route' => 'students.index',
            'permissions' => ['students.view'],
            'roles' => ['Secrétariat', 'Direction', 'Administrateur'],
            'keywords' => ['élève', 'matricule', 'parent', 'tuteur', 'dossier'],
            'steps' => [
                'Ouvrez Dossiers élèves puis cliquez sur Ajouter un élève si votre rôle le permet.',
                'Renseignez soigneusement l’identité en respectant les actes officiels.',
                'Ajoutez les coordonnées du père, de la mère ou du tuteur, surtout une adresse e-mail valide pour les notifications.',
                'Enregistrez puis ouvrez la fiche pour contrôler le matricule, les parents et les informations manquantes.',
                'Utilisez Modifier pour corriger le dossier sans créer de doublon.',
            ],
            'tips' => [
                'Recherchez d’abord le nom ou le matricule avant de créer un nouvel élève.',
            ],
        ],
        'student-import' => [
            'category' => 'students',
            'title' => 'Importer une liste d’élèves',
            'summary' => 'Préparer, contrôler et importer plusieurs élèves depuis Excel ou CSV.',
            'route' => 'students.import',
            'permissions' => ['students.import'],
            'roles' => ['Secrétariat', 'Administrateur'],
            'keywords' => ['excel', 'csv', 'import', 'modèle', 'doublons'],
            'steps' => [
                'Téléchargez toujours le modèle d’import depuis la page Importer.',
                'Conservez les en-têtes du modèle et complétez une ligne par élève.',
                'Chargez le fichier puis examinez l’aperçu, les erreurs et les avertissements.',
                'Corrigez le fichier si nécessaire avant de confirmer l’import définitif.',
                'Contrôlez ensuite le nombre total d’élèves et quelques dossiers au hasard.',
            ],
            'tips' => [
                'N’importez jamais deux fois le même fichier sans vérifier les avertissements de doublons.',
            ],
        ],
        'student-documents' => [
            'category' => 'students',
            'title' => 'Gérer les pièces, la fiche et la carte scolaire',
            'summary' => 'Joindre les documents scannés et produire les documents individuels.',
            'route' => 'students.index',
            'permissions' => ['students.view'],
            'roles' => ['Secrétariat', 'Direction'],
            'keywords' => ['acte naissance', 'photo', 'carte', 'fiche inscription', 'pièce'],
            'steps' => [
                'Ouvrez la fiche de l’élève puis la section Documents.',
                'Ajoutez un fichier lisible avec un nom explicite et le bon type de pièce.',
                'Vérifiez les pièces manquantes signalées par l’application.',
                'Utilisez Fiche d’inscription ou Carte scolaire pour générer le PDF correspondant.',
            ],
            'tips' => [
                'Utilisez une photo récente et bien cadrée pour la carte scolaire.',
            ],
        ],
        'classes' => [
            'category' => 'students',
            'title' => 'Créer et organiser les classes',
            'summary' => 'Définir les classes de l’année et consulter leurs effectifs.',
            'route' => 'classes.index',
            'permissions' => ['classes.manage'],
            'roles' => ['Secrétariat', 'Administrateur'],
            'keywords' => ['classe', 'niveau', 'capacité', 'effectif'],
            'steps' => [
                'Vérifiez que la bonne année scolaire est active.',
                'Créez la classe avec son niveau, son code et sa capacité.',
                'Ouvrez la classe pour consulter les inscrits et les places disponibles.',
                'Ne supprimez pas une classe déjà utilisée : corrigez-la ou rendez-la inactive.',
            ],
            'tips' => [
                'Utilisez des codes courts et cohérents, par exemple 6A, 3B ou TLED.',
            ],
        ],
        'enrollments' => [
            'category' => 'students',
            'title' => 'Inscrire un élève dans une classe',
            'summary' => 'Créer, modifier ou annuler l’inscription annuelle d’un élève.',
            'route' => 'enrollments.index',
            'permissions' => ['enrollments.view'],
            'roles' => ['Secrétariat', 'Direction'],
            'keywords' => ['inscription', 'réinscription', 'classe', 'année'],
            'steps' => [
                'Ouvrez Inscriptions puis choisissez l’élève, l’année et la classe.',
                'Sélectionnez Nouvelle inscription ou Réinscription selon la situation.',
                'Vérifiez la date et le statut avant d’enregistrer.',
                'Consultez la fiche d’inscription pour confirmer la classe et les frais attendus.',
            ],
            'tips' => [
                'Un élève ne doit avoir qu’une inscription active par année scolaire.',
            ],
        ],
        'tariffs' => [
            'category' => 'finance',
            'title' => 'Configurer les tarifs et échéances',
            'summary' => 'Définir les frais attendus par classe, tranche et date limite.',
            'route' => 'tariffs.index',
            'permissions' => ['settings.manage'],
            'roles' => ['Administrateur'],
            'keywords' => ['tarif', 'tranche', 'échéance', 'frais', 'montant'],
            'steps' => [
                'Ouvrez Tarifs et sélectionnez une classe de l’année active.',
                'Appliquez les valeurs par défaut si elles correspondent aux tarifs officiels.',
                'Vérifiez chaque type de frais, montant, période et date d’échéance.',
                'Enregistrez puis contrôlez le total attendu affiché pour la classe.',
            ],
            'tips' => [
                'Configurez les tarifs avant les premiers paiements pour obtenir des états financiers complets.',
            ],
        ],
        'payments' => [
            'category' => 'finance',
            'title' => 'Enregistrer un paiement et imprimer le reçu',
            'summary' => 'Encaisser un règlement, le répartir sur les frais et remettre un reçu.',
            'route' => 'payments.index',
            'permissions' => ['payments.view'],
            'roles' => ['Comptable', 'Administrateur'],
            'keywords' => ['paiement', 'reçu', 'encaissement', 'espèces', 'mobile money'],
            'steps' => [
                'Recherchez l’élève depuis Paiements puis cliquez sur Encaisser.',
                'Choisissez la tranche ou le type de frais et saisissez le montant réellement reçu.',
                'Sélectionnez le moyen de paiement et ajoutez une référence si nécessaire.',
                'Relisez le total avant de confirmer : un numéro de reçu unique est généré.',
                'Imprimez ou téléchargez le reçu et remettez-le au payeur.',
            ],
            'tips' => [
                'En cas d’erreur, annulez le paiement avec un motif ; ne modifiez jamais un reçu validé à la main.',
            ],
        ],
        'unpaid' => [
            'category' => 'finance',
            'title' => 'Suivre les impayés et le relevé d’un élève',
            'summary' => 'Identifier les restes à payer et produire une situation individuelle.',
            'route' => 'payments.unpaid',
            'permissions' => ['payments.reports'],
            'roles' => ['Comptable', 'Direction'],
            'keywords' => ['impayé', 'reste', 'solde', 'relevé', 'situation'],
            'steps' => [
                'Ouvrez Paiements puis Tous les impayés.',
                'Filtrez par année, classe ou élève pour réduire la liste.',
                'Ouvrez le relevé individuel pour voir les frais attendus, les versements et le solde.',
                'Exportez la liste ou imprimez la situation lorsque cela est nécessaire.',
            ],
            'tips' => [
                'Un reste incorrect vient souvent d’un tarif manquant ou d’un paiement affecté à la mauvaise tranche.',
            ],
        ],
        'accounting' => [
            'category' => 'finance',
            'title' => 'Tenir le journal de caisse et les dépenses',
            'summary' => 'Consulter les entrées, enregistrer les sorties et éditer le bilan.',
            'route' => 'accounting.cash-journal',
            'permissions' => ['payments.reports'],
            'roles' => ['Comptable', 'Direction'],
            'keywords' => ['caisse', 'dépense', 'bilan', 'journal', 'recette'],
            'steps' => [
                'Ouvrez Comptabilité pour consulter le journal de caisse de la période.',
                'Enregistrez chaque dépense avec sa catégorie, son bénéficiaire et sa référence justificative.',
                'Annulez une dépense erronée avec un motif au lieu de la supprimer.',
                'Utilisez le bilan pour comparer recettes, dépenses et solde.',
            ],
            'tips' => [
                'Conservez le justificatif papier ou numérique correspondant à chaque dépense.',
            ],
        ],
        'financial-reports' => [
            'category' => 'finance',
            'title' => 'Produire les rapports financiers',
            'summary' => 'Filtrer, imprimer et exporter les situations par classe et échéance.',
            'route' => 'reports.payment-situation',
            'permissions' => ['payments.reports'],
            'roles' => ['Comptable', 'Direction'],
            'keywords' => ['rapport', 'excel', 'pdf', 'échéancier', 'situation financière'],
            'steps' => [
                'Ouvrez Rapports puis Situation financière ou Échéances.',
                'Choisissez l’année, la classe et les critères de solde.',
                'Contrôlez les totaux affichés avant l’export.',
                'Téléchargez le PDF pour l’impression ou le fichier Excel/CSV pour l’analyse.',
            ],
            'tips' => [
                'Les filtres restent appliqués au document exporté.',
            ],
        ],
        'attendance' => [
            'category' => 'school-life',
            'title' => 'Faire l’appel et justifier une absence',
            'summary' => 'Créer une séance, pointer les élèves et corriger les statuts.',
            'route' => 'attendance.index',
            'permissions' => ['attendance.view'],
            'roles' => ['Surveillant', 'Enseignant', 'Direction'],
            'keywords' => ['absence', 'retard', 'présence', 'justification', 'appel'],
            'steps' => [
                'Ouvrez Absences, choisissez la classe et la date, puis créez la séance.',
                'Marquez chaque élève présent, absent ou en retard.',
                'Pour un retard, indiquez le nombre de minutes ; ajoutez le motif lorsqu’il est connu.',
                'Enregistrez la séance puis corrigez ou justifiez les dossiers reçus plus tard.',
                'Utilisez l’historique individuel ou le PDF pour un suivi détaillé.',
            ],
            'tips' => [
                'Une absence ou un retard enregistré peut déclencher un e-mail au parent disposant d’une adresse valide.',
            ],
        ],
        'exit-authorizations' => [
            'category' => 'school-life',
            'title' => 'Créer une autorisation de sortie',
            'summary' => 'Enregistrer une sortie, son motif, le responsable et produire le document.',
            'route' => 'exit-authorizations.index',
            'permissions' => ['students.export'],
            'roles' => ['Secrétariat', 'Direction'],
            'keywords' => ['sortie', 'autorisation', 'motif', 'parent'],
            'steps' => [
                'Recherchez l’élève puis ouvrez Nouvelle autorisation.',
                'Saisissez la date, l’heure, le motif, la destination et la personne responsable.',
                'Relisez les informations puis enregistrez.',
                'Imprimez le PDF et faites signer le document selon la procédure du lycée.',
            ],
            'tips' => [
                'Ne remettez jamais une autorisation sans vérifier l’identité de la personne qui récupère l’élève.',
            ],
        ],
        'timetables' => [
            'category' => 'school-life',
            'title' => 'Créer et imprimer un emploi du temps',
            'summary' => 'Organiser les cours par classe, jour, heure, matière et enseignant.',
            'route' => 'timetables.index',
            'permissions' => ['timetables.view'],
            'roles' => ['Secrétariat', 'Enseignant', 'Surveillant'],
            'keywords' => ['emploi du temps', 'cours', 'salle', 'professeur'],
            'steps' => [
                'Sélectionnez l’année et la classe dans Emplois du temps.',
                'Créez ou modifiez les créneaux avec l’heure, la matière, l’enseignant et la salle.',
                'Vérifiez qu’aucun cours ne se chevauche dans la même classe.',
                'Enregistrez puis téléchargez le PDF pour affichage.',
            ],
            'tips' => [
                'Utilisez les mêmes noms de matières que dans le module Matières.',
            ],
        ],
        'teacher-sheets' => [
            'category' => 'school-life',
            'title' => 'Imprimer les feuilles d’émargement',
            'summary' => 'Produire les feuilles utilisées pour la présence des enseignants.',
            'route' => 'teacher-attendance-sheets.index',
            'permissions' => ['timetables.print'],
            'roles' => ['Secrétariat', 'Direction'],
            'keywords' => ['émargement', 'enseignant', 'signature', 'cours'],
            'steps' => [
                'Ouvrez Émargements et sélectionnez la période souhaitée.',
                'Choisissez les classes ou les jours concernés.',
                'Prévisualisez les lignes issues des emplois du temps.',
                'Téléchargez le PDF puis imprimez-le pour les signatures.',
            ],
            'tips' => [
                'Corrigez d’abord l’emploi du temps si un cours manque sur la feuille.',
            ],
        ],
        'subjects' => [
            'category' => 'pedagogy',
            'title' => 'Configurer les matières et coefficients',
            'summary' => 'Créer les matières et les associer aux classes avec le bon coefficient.',
            'route' => 'subjects.index',
            'permissions' => ['subjects.manage'],
            'roles' => ['Administrateur'],
            'keywords' => ['matière', 'coefficient', 'classe', 'discipline'],
            'steps' => [
                'Créez la matière avec un nom et un code cohérents.',
                'Associez-la à chaque classe concernée pour l’année active.',
                'Renseignez le coefficient utilisé dans le calcul des moyennes.',
                'Vérifiez la liste complète avant la création des évaluations.',
            ],
            'tips' => [
                'Modifier un coefficient après la saisie des notes change les moyennes recalculées.',
            ],
        ],
        'grades' => [
            'category' => 'pedagogy',
            'title' => 'Créer une évaluation et saisir les notes',
            'summary' => 'Préparer un devoir, noter les élèves et verrouiller la saisie.',
            'route' => 'grades.index',
            'permissions' => ['grades.view'],
            'roles' => ['Enseignant', 'Direction'],
            'keywords' => ['note', 'devoir', 'évaluation', 'verrouillage', 'moyenne'],
            'steps' => [
                'Choisissez l’année, la classe, la période et la matière.',
                'Créez l’évaluation avec son titre, son type, sa date et son barème.',
                'Saisissez une note ou un statut d’absence pour chaque élève.',
                'Enregistrez et vérifiez les statistiques de l’évaluation.',
                'Verrouillez l’évaluation lorsqu’elle est validée afin d’éviter les modifications accidentelles.',
            ],
            'tips' => [
                'Seuls les utilisateurs autorisés peuvent déverrouiller une évaluation.',
            ],
        ],
        'grade-import' => [
            'category' => 'pedagogy',
            'title' => 'Importer ou exporter les notes',
            'summary' => 'Utiliser le modèle de notes pour accélérer une saisie collective.',
            'route' => 'grades.index',
            'permissions' => ['grades.view'],
            'roles' => ['Enseignant', 'Direction'],
            'keywords' => ['import notes', 'excel', 'csv', 'barème'],
            'steps' => [
                'Ouvrez l’évaluation puis téléchargez son modèle d’import.',
                'Complétez uniquement les colonnes prévues sans modifier les matricules.',
                'Chargez le fichier et examinez l’aperçu des nouvelles notes et des mises à jour.',
                'Corrigez toutes les erreurs avant de confirmer.',
                'Exportez ensuite la feuille finale pour vos archives si nécessaire.',
            ],
            'tips' => [
                'Le barème et les matricules doivent correspondre exactement à l’évaluation ouverte.',
            ],
        ],
        'report-cards' => [
            'category' => 'pedagogy',
            'title' => 'Générer et imprimer les bulletins',
            'summary' => 'Calculer les moyennes, contrôler les appréciations et produire les PDF.',
            'route' => 'report-cards.index',
            'permissions' => ['report_cards.view'],
            'roles' => ['Direction', 'Administrateur'],
            'keywords' => ['bulletin', 'moyenne', 'rang', 'appréciation', 'pdf'],
            'steps' => [
                'Choisissez l’année, le trimestre et la classe.',
                'Vérifiez que toutes les évaluations attendues sont saisies et verrouillées.',
                'Générez les bulletins pour calculer moyennes, rangs et appréciations.',
                'Relisez les décisions et observations administratives.',
                'Imprimez un bulletin individuel ou le lot complet de la classe.',
            ],
            'tips' => [
                'Régénérez les bulletins après toute correction autorisée d’une note.',
            ],
        ],
        'class-council' => [
            'category' => 'pedagogy',
            'title' => 'Tenir le conseil de classe',
            'summary' => 'Examiner les résultats, fixer les décisions et verrouiller le conseil.',
            'route' => 'class-council.index',
            'permissions' => ['report_cards.view'],
            'roles' => ['Direction'],
            'keywords' => ['conseil', 'décision', 'admis', 'redoublement', 'pv'],
            'steps' => [
                'Sélectionnez la classe et la période du conseil.',
                'Examinez les moyennes, rangs, appréciations et situations particulières.',
                'Corrigez les décisions proposées lorsque le conseil le décide.',
                'Imprimez le procès-verbal et les relevés nécessaires.',
                'Verrouillez le conseil après validation ; le déverrouillage doit rester exceptionnel.',
            ],
            'tips' => [
                'La liste des rachats annuels aide à repérer les élèves proches de la moyenne de passage.',
            ],
        ],
        'mock-exams' => [
            'category' => 'pedagogy',
            'title' => 'Organiser un examen blanc',
            'summary' => 'Gérer candidats, anonymat, salles, copies, notes et décisions du jury.',
            'route' => 'mock-exams.index',
            'permissions' => ['mock_exams.view'],
            'roles' => ['Secrétariat', 'Direction', 'Enseignant'],
            'keywords' => ['examen blanc', 'anonymat', 'jury', 'salle', 'copies'],
            'steps' => [
                'Créez l’examen avec l’année, les classes, les dates et les matières.',
                'Synchronisez les candidats puis générez les numéros d’anonymat.',
                'Répartissez les candidats dans les salles et imprimez les listes.',
                'Suivez les sujets, surveillants, absents et copies remises.',
                'Saisissez les notes, calculez les résultats puis enregistrez les décisions du jury.',
            ],
            'tips' => [
                'Imprimez le bordereau de réception des copies avant le début des corrections.',
            ],
        ],
        'communications' => [
            'category' => 'documents',
            'title' => 'Envoyer des notifications par e-mail',
            'summary' => 'Informer les parents ou le personnel et suivre l’historique des envois.',
            'route' => 'communications.index',
            'permissions' => ['communications.view'],
            'roles' => ['Direction', 'Secrétariat', 'Comptable'],
            'keywords' => ['email', 'resend', 'annonce', 'parent', 'historique'],
            'steps' => [
                'Ouvrez Notifications puis l’onglet Envoyer.',
                'Choisissez les parents, une classe, tout le personnel ou un rôle précis.',
                'Rédigez un objet clair et un message sans informations inutiles.',
                'Contrôlez le nombre de destinataires et le quota disponible avant de confirmer.',
                'Consultez Historique pour voir les messages envoyés, différés ou échoués et relancer si nécessaire.',
            ],
            'tips' => [
                'Les paiements, absences, retards et changements de statut peuvent déjà produire des messages automatiques.',
            ],
        ],
        'certificates' => [
            'category' => 'documents',
            'title' => 'Créer un certificat administratif',
            'summary' => 'Produire un certificat avec numéro, identité et signature officielle.',
            'route' => 'certificates.index',
            'permissions' => ['students.export'],
            'roles' => ['Secrétariat', 'Direction'],
            'keywords' => ['certificat', 'attestation', 'document officiel', 'signature'],
            'steps' => [
                'Ouvrez Certificats puis cliquez sur Nouveau certificat.',
                'Choisissez l’élève et le type de document.',
                'Vérifiez l’année, le motif, la date et le signataire.',
                'Enregistrez puis ouvrez le PDF avant impression.',
            ],
            'tips' => [
                'Contrôlez toujours l’orthographe du nom de l’élève avant de remettre un document officiel.',
            ],
        ],
        'print-center' => [
            'category' => 'documents',
            'title' => 'Utiliser le centre d’impression',
            'summary' => 'Retrouver rapidement les PDF disponibles pour une classe ou un élève.',
            'route' => 'print-center.index',
            'permissions' => [],
            'roles' => ['Tous les utilisateurs selon permissions'],
            'keywords' => ['impression', 'pdf', 'document', 'centre'],
            'steps' => [
                'Ouvrez Centre d’impression depuis le haut de la page.',
                'Choisissez l’année, la classe ou recherchez un élève.',
                'Filtrez par type : élèves, finances, notes, examens ou vie scolaire.',
                'Ouvrez le document souhaité puis utilisez la commande d’impression du navigateur.',
            ],
            'tips' => [
                'Seuls les documents autorisés pour votre rôle sont proposés.',
            ],
        ],
        'exports' => [
            'category' => 'documents',
            'title' => 'Importer, exporter et produire les rapports',
            'summary' => 'Centraliser les extractions Excel/CSV et les listes PDF.',
            'route' => 'exports.index',
            'permissions' => ['students.import', 'students.export', 'payments.reports', 'grades.view', 'attendance.view', 'mock_exams.view'],
            'roles' => ['Secrétariat', 'Direction', 'Comptable'],
            'keywords' => ['export', 'excel', 'csv', 'pdf', 'rapport'],
            'steps' => [
                'Ouvrez Imports / Exports ou Rapports depuis le menu.',
                'Choisissez le domaine et appliquez les filtres d’année, classe ou période.',
                'Vérifiez le nombre de lignes et les totaux avant téléchargement.',
                'Conservez les exports contenant des données personnelles dans un emplacement protégé.',
            ],
            'tips' => [
                'Un export respecte les permissions de l’utilisateur connecté.',
            ],
        ],
        'staff' => [
            'category' => 'administration',
            'title' => 'Gérer les comptes du personnel',
            'summary' => 'Créer, modifier, désactiver et réinitialiser les accès utilisateurs.',
            'route' => 'staff.index',
            'permissions' => ['users.manage'],
            'roles' => ['Administrateur'],
            'keywords' => ['personnel', 'utilisateur', 'compte', 'mot de passe'],
            'steps' => [
                'Ouvrez Personnel puis créez un compte avec un identifiant unique.',
                'Attribuez le rôle correspondant aux responsabilités réelles de la personne.',
                'Remettez le mot de passe temporaire de manière confidentielle.',
                'Désactivez immédiatement les comptes des personnes qui quittent l’établissement.',
                'Utilisez Réinitialiser le mot de passe uniquement après vérification de l’identité.',
            ],
            'tips' => [
                'Évitez les comptes partagés : chaque action doit pouvoir être rattachée à une personne.',
            ],
        ],
        'roles' => [
            'category' => 'administration',
            'title' => 'Configurer les rôles et permissions',
            'summary' => 'Limiter chaque utilisateur aux écrans et actions nécessaires.',
            'route' => 'staff.roles.index',
            'permissions' => ['roles.manage'],
            'roles' => ['Administrateur'],
            'keywords' => ['rôle', 'permission', 'accès', 'sécurité'],
            'steps' => [
                'Ouvrez Personnel puis Rôles et accès.',
                'Sélectionnez un rôle et examinez toutes ses permissions.',
                'Ajoutez seulement les actions nécessaires au travail quotidien.',
                'Testez les modifications avec un compte du rôle concerné.',
            ],
            'tips' => [
                'Ne donnez pas les permissions d’administration, d’annulation ou de déverrouillage sans nécessité.',
            ],
        ],
        'audit-logs' => [
            'category' => 'administration',
            'title' => 'Consulter le journal d’activité et les connexions',
            'summary' => 'Rechercher qui a modifié une donnée et quand une connexion a eu lieu.',
            'route' => 'activity-logs.index',
            'permissions' => ['activity_logs.view'],
            'roles' => ['Direction', 'Administrateur'],
            'keywords' => ['journal', 'audit', 'connexion', 'historique', 'sécurité'],
            'steps' => [
                'Ouvrez Journal et filtrez par utilisateur, action, date ou élément.',
                'Ouvrez une ligne pour comparer les anciennes et nouvelles valeurs.',
                'Consultez l’historique des connexions pour contrôler les adresses IP et les échecs.',
                'Conservez les éléments utiles avant toute enquête ou correction importante.',
            ],
            'tips' => [
                'Le journal aide à comprendre une modification ; il ne remplace pas les sauvegardes.',
            ],
        ],
        'backups' => [
            'category' => 'administration',
            'title' => 'Créer et contrôler les sauvegardes',
            'summary' => 'Télécharger une copie manuelle et comprendre la sauvegarde automatique.',
            'route' => 'settings.backups.index',
            'permissions' => ['settings.manage'],
            'roles' => ['Administrateur'],
            'keywords' => ['sauvegarde', 'restauration', 'base de données', 'archive'],
            'steps' => [
                'Ouvrez Paramètres puis Sauvegardes pour consulter les copies disponibles.',
                'Lancez une sauvegarde manuelle avant une importation ou une opération exceptionnelle.',
                'Téléchargez la copie uniquement vers un emplacement protégé.',
                'Contrôlez les alertes automatiques et le résultat de l’exercice mensuel de restauration.',
            ],
            'tips' => [
                'Une sauvegarde n’est fiable que si sa restauration a été testée.',
            ],
        ],
    ],
];
